name: Continuous Integration

on:
  [ push,pull_request ]

jobs:
  build:
    name: Continuous Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Check cmake version
        run: cmake --version

      - name: Creating build directory
        run: cmake -E make_directory ./build

      - name: Precompilation
        working-directory: ./build
        run: cmake .. -DCMAKE_BUILD_TYPE=Release

      - name: Compilation
        working-directory: ./build
        run: cmake --build . --config Release

      - name: Testing
        working-directory: ./build
        run: ctest
